package br.com.ecommerce.ecom.enums;

public enum ErrorCode {
    EMAIL_ALREADY_IN_USE,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    AUTHENTICATION_FAILED,
    RESOURCE_NOT_FOUND,
    VALIDATION_FAILED,
    INVALID_REQUEST,
    DUPLICATE_RESOURCE,
    EXTERNAL_SERVICE_UNAVAILABLE,
    KEYCLOAK_AUTHENTICATION_FAILED,
    KEYCLOAK_CREATE_USER_FAILED,
    USER_INACTIVE,
    INTERNAL_SERVER_ERROR,
    INVALID_CART_OPERATION,
    INVALID_ORDER_STATUS,
    EMPTY_CART
}
