package br.com.ecommerce.ecom.enums;

public enum ErrorCode {
    EMAIL_ALREADY_IN_USE,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    AUTHENTICATION_FAILED,
    RESOURCE_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    ORDER_NOT_FOUND,
    VALIDATION_FAILED,
    INVALID_REQUEST,
    DUPLICATE_RESOURCE,
    EXTERNAL_SERVICE_UNAVAILABLE,
    KEYCLOAK_AUTHENTICATION_FAILED,
    KEYCLOAK_CREATE_USER_FAILED,
    KEYCLOAK_COMMUNICATION_ERROR,
    UNKNOWN_ERROR,
    USER_INACTIVE,
    INTERNAL_SERVER_ERROR,
    CART_ITEM_NOT_FOUND,
    INVALID_CART_OPERATION,
    CART_DOES_NOT_EXIST
}
